# Site settings
title: Nilops.com
email: ralph@nilops.com
description: > # this means to ignore newlines until "baseurl:"
  nilops.com is all about the goal of eliminating all the ops by brute force or automation
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nilops.com" # the base hostname & protocol for your site
twitter_username: nilops_
github_username:  nilops

# Build settings
markdown: kramdown
tsc: /usr/local/bin/tsc
js_dest: js/
